### ISSUE TITLE
Security Checklist

### ISSUE THREAD

**Issue by hwine** [taskcluster/websocktunnel#13]
As discussed in meeting, not all of these may be applicable.

Risk Management
---------------
* [ ] The service must have performed a Rapid Risk Assessment and have a Risk Record bug
* [ ] Public staging and production endpoints must be added to the [security baseline](https://github.com/mozilla-services/foxsec/blob/master/services/README.md)
 
Infrastructure
--------------
 
* [x] Access and application logs must be archived for a minimum of 90 days
* [x] Use [Modern](https://wiki.mozilla.org/Security/Server_Side_TLS#Modern_compatibility) or [Intermediate](https://wiki.mozilla.org/Security/Server_Side_TLS#Intermediate_compatibility) TLS
* [ ] Set HSTS to 31536000 (1 year)
  * `strict-transport-security: max-age=31536000`
* [ ] Set HPKP to 5184000 (60 days)
  * `Public-Key-Pins: max-age=5184000; pin-sha256="WoiWRyIOVNa9ihaBciRSC7XHjliYS9VwUGOIud4PB18="; pin-sha256="r/mIkG3eEpVdm+u/ko/cwxzOMo1bk4TyHIlByibiA5E="; pin-sha256="YLh1dUR9y6Kja30RrAn7JKnbQG/uEtLMkBgFF2Fuihg="; pin-sha256="sRHdihwgkaib1P1gxX8HFszlD+7/gTfNvuAybgLPNis=";`
    * Start with max-age set to 5 minutes (`max-age=300`) and increase progressively
    * The first two pins are for Digicert EV and DV roots, the last two are for Let's Encrypt X3 and X4 intermediates (LE is only used for backup)
  * [ ] If the service is not hosted under `services.mozilla.com`, it must be manually added to [Firefox's preloaded pins](https://dxr.mozilla.org/mozilla-central/source/security/manager/tools/PreloadedHPKPins.json#184).
* If service has an admin panels, it must:
  * [ ] only be available behind Mozilla VPN (which provides MFA)
  * [ ] require Auth0 authentication
 
Development
-----------
* [ ] Sign all release tags, and ideally commits as well
  * Developers should [configure git to sign all tags](http://micropipes.com/blog//2016/08/31/signing-your-commits-on-github-with-a-gpg-key/) and upload their PGP fingerprint to https://login.mozilla.com
  * The signature verification will eventually become a requirement to shipping a release to staging & prod: the tag being deployed in the pipeline must have a matching tag in git signed by a project owner. This control is designed to reduce the risk of a 3rd party GitHub integration from compromising our source code.
* [ ] Keep 3rd-party libraries up to date
  * Use [NSP](https://nodesecurity.io/) or [GreenKeeper](https://greenkeeper.io/ Greenkeeper) for NodeJS applications
  * For Python applications, enable pyup security updates:
    * Add a pyup config to your repo (example config: https://github.com/mozilla-services/antenna/blob/master/.pyup.yml)
    * From the "add a team" dropdown for your repo add the relevant "Approved Mozilla PyUp Configuration" team for your github org (e.g. for [mozilla](https://github.com/orgs/mozilla/teams/approved-mozilla-pyup-configuration) and [mozilla-services](https://github.com/orgs/mozilla-services/teams/approved-mozilla-pyup-configuration)) and grant it write permission.
    * Notify secops@mozilla.com to enable the integration in pyup
    * Consider using ``pip list --outdated`` or [requires.io](https://requires.io/) too
* [ ] Integrate static code analysis in CI, and avoid merging code with issues
    * Javascript applications should use ESLint with the [Mozilla ruleset](https://developer.mozilla.org/en-US/docs/ESLint)
    * Python applications should use [Bandit](https://github.com/openstack/bandit)
    * Go applications should use the [Go Meta Linter](https://github.com/alecthomas/gometalinter)
    * Use whitelisting mechanisms in these tools to deal with false positives
 
Dual Sign Off
------------
* [ ] Services that push data to Firefox clients must require a dual sign off on every change, implemented in their admin panels
  * This mechanism must be reviewed and approved by the Firefox Operations Security team before being enabled in production
 
Logging
-------
* [x] Publish detailed logs in [mozlog](https://github.com/mozilla-services/Dockerflow/blob/master/docs/mozlog.md) format (**APP-MOZLOG**)
  * Business logic must be logged with app specific codes (see [FxA](https://github.com/mozilla/fxa-auth-server/blob/master/docs/api.md#defined-errors))
  * Access control failures must be logged at WARN level
 
Security Headers
----------------
* [ ] Must have a CSP with
  * [ ] a report-uri pointing to the service's own `/__cspreport__` endpoint
  * [ ] web API responses should return `default-src 'none'; frame-ancestors 'none'; base-uri 'none'; report-uri /__cspreport__` to disallowing all content rendering, framing, and report violations
  * [ ] if default-src is not `none`, frame-src, and object-src should be `none` or only allow specific origins
  * [ ] no use of unsafe-inline or unsafe-eval in script-src, style-src, and img-src
* [ ] Web APIs must set a non-HTML content-type on all responses, including 300s, 400s and 500s
* [ ] Set the Secure and HTTPOnly flags on [Cookies](https://wiki.mozilla.org/Security/Guidelines/Web_Security#Cookies), and use sensible Expiration
* [ ] Make sure your application gets an A+ on the [Mozilla Observatory](https://observatory.mozilla.org/)
* [ ] Verify your application doesn't have any failures on the [Security Baseline](https://github.com/mozilla-services/foxsec/blob/master/tools/baseline-scan/results/Baseline-Services.md).
  * Contact secops@ or ping 'psiinon' on github to document exceptions to the baseline, mark csrf exempt forms, etc.
* [x] Web APIs should export an OpenAPI (Swagger) to facilitate automated vulnerability tests
 
Databases
---------
* [x] All SQL queries must be parameterized, not concatenated
* [x] Applications must use accounts with limited GRANTS when connecting to databases
  * In particular, applications **must not use admin or owner accounts**, to decrease the impact of a sql injection vulnerability.
 
Common issues
-------------
* [x] User data must be [escaped for the right context](https://www.owasp.org/index.php/XSS_(Cross_Site_Scripting)_Prevention_Cheat_Sheet#XSS_Prevention_Rules_Summary) prior to reflecting it
  * When inserting user generated html into an html context:
    * Python applications should use [Bleach](https://github.com/mozilla/bleach)
    * Javascript applications should use [DOMPurify](https://github.com/cure53/DOMPurify/)
* [x] Apply sensible limits to user inputs, see [input validation](https://wiki.mozilla.org/WebAppSec/Secure_Coding_Guidelines#Input_Validation)
  * POST body size should be small (<500kB) unless explicitely needed
* [x] When managing permissions, make sure access controls are enforced server-side
* [x] If handling cryptographic keys, must have a mechanism to handle quarterly key rotations
  * Keys used to sign sessions don't need a rotation mechanism if destroying all sessions is acceptable in case of emergency.
* [x] Do not proxy requests from users without strong limitations and filtering (see [Pocket UserData vulnerability](https://www.gnu.gl/blog/Posts/multiple-vulnerabilities-in-pocket/)). Don't proxy requests to [link local, loopback, or private networks](https://en.wikipedia.org/wiki/Reserved_IP_addresses#IPv4) or DNS that resolves to addresses in those ranges (i.e. 169.254.0.0/16, 127.0.0.0/8, 10.0.0.0/8, 100.64.0.0/10, 172.16.0.0/12, 192.168.0.0/16, 198.18.0.0/15).

**Comment by petemoore** [comment]
> Do not proxy requests from users without strong limitations and filtering (see Pocket UserData vulnerability). Don't proxy requests to link local, loopback, or private networks or DNS that resolves to addresses in those ranges (i.e. 169.254.0.0/16, 127.0.0.0/8, 10.0.0.0/8, 100.64.0.0/10, 172.16.0.0/12, 192.168.0.0/16, 198.18.0.0/15).

@hwine webhooktunnel acts as a reverse tunnel to workers in our vpn, allowing client web browser connections from the internet to proxy arbitrary requests through a central proxy host to a port on the worker. The listener that accepts these connections on the worker is running in the same OS process as the code that build the firefox binaries.

I would propose we resist deploying this feature until the security audit is completed, as I believe this may be deemed to pose a not-insignificant threat to the security of the firefox releases. I'm not sure what security benefit(s) this setup offers over that of a direct connection, which we deemed to be too dangerous in our livelog tool, which we subsequently disabled on workers running inside our VPN.

**Comment by jvehent** [comment]
> webhooktunnel acts as a reverse tunnel to workers in our vpn, allowing client web browser connections from the internet to proxy arbitrary requests through a central proxy host to a port on the worker.

Proxying on purpose is fine, as long as you implement strict validation of what is being proxied, so it cannot be used to retrieve private resources.

> The listener that accepts these connections on the worker is running in the same OS process as the code that builds the firefox binaries.

I don't think the issue is at this level, but rather at the level of the proxy itself.

> I would propose we resist deploying this feature until the security audit is completed

The expectation here is that the TC team would run through this checklist and perform its own code review (we can answer as many questions as you'd like). If specific areas of the code need to be audited, the security team can have a look, but there is so much code written at Mozilla that we don't have the means to review everything.

**Comment by ckousik** [comment]
@petemoore For added context, the architecture is such that it is up to the worker what it wishes to expose on the proxy. Webhooktunnel only proxies HTTP requests and WebSocket connections, and it is currently not capable of proxying arbitrary TCP. You cannot hijack the underlying TCP connection because of the way the proxy is structured. It will first transfer data from the client to the worker, and then stream the response from the worker to the client. If the client or the worker wishes to send data while the proxy is streaming the other way that just won't work (it will fill up the buffer but since no one is reading the writes will fail). The websocket proxying component also verifies that all data over the connection is valid websocket data. Both connections (proxy to client and client to proxy) are using HTTPS. Webhooktunnel will also host different workers at different URLs(*.tcproxy.build). But I agree that a more rigorous security review should be performed before this is deployed into production.

**Comment by hwine** [comment]
> But I agree that a more rigorous security review should be performed before this is deployed into production.

Step 1 of any security review is to complete the checklist. By complete, I mean "review and understand how each item impacts this code". That could be one or more of the following:

- already done 🎉 
- link to bug/issue where it's scheduled to be done 
- explanation of why it doesn't apply (e.g. "no permanent service", "our team does XXX instead")
- discussing with secops what is meant by the item, and coming to an one of the above understandings.

That lets any subsequent review focus on the remaining app-specific functionality, knowing that "the basics" are covered. Deep discussion of the app-specific functionality is better addressed outside the checklist review, where we can all give the issues appropriate focus.

**Comment by jonasfj** [comment]
I see most of this an not-applicable, and many of the things that could be applied as unnecessary.. This is protecting livelogs and facilitating interactive sessions by proxing requests...

We use a fresh domain name per worker life-cycle... So I don't see much benefit in CSP, HSTS and HPKP headers... There is no cookies, etc. There is not really anything protected clientside on these domains, so cross scripting is of little concern.

* [ ] The service must have performed a Rapid Risk Assessment and have a Risk Record bug
* [ ] Public staging and production endpoints must be added to the [security baseline](https://github.com/mozilla-services/foxsec/blob/master/services/README.md)
* [x] Access and application logs must be archived for a minimum of 90 days
* [x] Use [Modern](https://wiki.mozilla.org/Security/Server_Side_TLS#Modern_compatibility) or [Intermediate](https://wiki.mozilla.org/Security/Server_Side_TLS#Intermediate_compatibility) TLS
* [x] If handling cryptographic keys, must have a mechanism to handle quarterly key rotations
* [ ] Sign all release tags, and ideally commits as well
* [ ] Keep 3rd-party libraries up to date
      (not sure this is realistic with golang)
* [ ] Integrate static code analysis in CI, and avoid merging code with issues
    * Go applications should use the [Go Meta Linter](https://github.com/alecthomas/gometalinter)
* [x] Publish detailed logs in [mozlog](https://github.com/mozilla-services/Dockerflow/blob/master/docs/mozlog.md) format (**APP-MOZLOG**)
* [ ] Make sure your application gets an A+ on the [Mozilla Observatory](https://observatory.mozilla.org/)
* [x] Web APIs must set a non-HTML content-type on all responses, including 300s, 400s and 500s
* [ ] Set HSTS to 31536000 (1 year)

@ckousik, I suspect you might be able to take on:
* [ ] Sign all release tags, and ideally commits as well (ie. check that you've configured you git client to sign commits and tags)
* [ ] Integrate static code analysis in CI, and avoid merging code with issues
    * Go applications should use the [Go Meta Linter](https://github.com/alecthomas/gometalinter)
* [ ] Set HSTS to 31536000 (1 year), (mostly useless as domains aren't reused)
* [ ] Review https://observatory.mozilla.org/analyze.html?host=tasks.build I dont' think HPKP is worth risking, and CSP if applied should be wide open... we do wish to allow embedding in iframes...
* [ ] Keep 3rd-party libraries up to date  (not sure this is realistic with golang)

The last one ties into vendoring things up. We should probably do this with [dep](https://github.com/golang/dep). I'm not sure there is any services that will check if 3rd party libraries have been updated.
If you want you could try to write a hook task that does a git clone and tries to check that dependencies are up-to-date, but I think this is too hard, and that we should not do it... Unless there is a nice service for doing exactly this..

I can take a look at:
* [ ] The service must have performed a Rapid Risk Assessment and have a Risk Record bug
* [ ] Public staging and production endpoints must be added to the [security baseline](https://github.com/mozilla-services/foxsec/blob/master/services/README.md)

@ckousik, do we even have production end-points as such? ^ if you don't have credentials is there anything even remotely useful that you can scan..

I think we have done an RRA for this... @hwine what is a "Risk Record bug"? and is there anything missing wrt. the RRA?

**Comment by hwine** [comment]
@jonasfj I'm going to reply in several different comments -- there's a lot to unpack in [your comment](https://github.com/taskcluster/webhooktunnel/issues/13#issuecomment-344439135). This one I'll deal with the process questions.

## RRA Process

> I think we have done an RRA for this... 

We held the initial interview to asses the scope & "kick off" the process. We're in the middle of the RRA now, and hope to conclude it "soonish" (which is why we're chatting about the checklist).

The checklist is similar to the "health history" you fill out at a new doctor's office. It documents how things currently are, including any WIP or plans.

> what is a "Risk Record bug"? and 

The RRA document is a standardized document that is a "worksheet" for the process.  The checklist covers a lot of details that should be easily answerable. We work with both data sets to come up with a risk statement and a set of recommendations.

The output of the RRA is a set of recommendations, which are recorded both in the RRA document, and in the Risk Record bug (which has not yet been created for this).

> is there anything missing wrt. the RRA?

Several things:
 - completion of checklist (*not implementation of every item*) *<-- need TC team's input*
 - risk assessment *[hwine]*
 - recommendations and documentation *[hwine]*

It's possible, even likely, that some of the recommendations might be related to checklist items, as they are based on general best practices. But each service is assessed individually.

**Comment by hwine** [comment]
@jonasfj part 2 response to [your comment](https://github.com/taskcluster/webhooktunnel/issues/13#issuecomment-344439135)

> This is protecting livelogs and facilitating interactive sessions by proxing requests...

We'd like to keep these things separate:
 - the service (proxy)
 - the initial services utilizing the proxy service (livelogs & interactive sessions)

The initial uses inform the RRA by letting us characterize the data classification handled by the service. I.e. ideally, the RRA will let you know which other services you can hook up to the proxy without needing another review.

> We use a fresh domain name per worker life-cycle... So I don't see much benefit in CSP, HSTS and HPKP headers... There is no cookies, etc. There is not really anything protected clientside on these domains, so cross scripting is of little concern.

The "clientside" I'm concerned with is the browser/machine of the developer accessing a service via the proxy. That browser/machine will have some valuable assets. :)

⏫ is an example of the dialog we'll have as the checklist fills in and the recommendations develop.

**Comment by jonasfj** [comment]
As discussed in meeting, not all of these may be applicable.

Okay, I've crossed out the points I think we've done.
Striked out the things I think don't apply.

Left unresolved issues as unchecked boxes. I'm not sure we should invest resources in fixing any of them.
This is not a critical service, attacks seems unlikely and it seems hard to do anything with it...

Hence, I recommend that we label those as security recommendations not adopted due to reward/risk being low...

@hwine is this what you are looking for? ^ I could file issues for the few worth considering. But I'm tempted to declare them all no worth doing. They are more like nice to have hardening.

Note: If it seems like I'm just trying to make this thing go away, then there is some truth to that :)
(at-least I'm willing to admit I'm being naughty -- don't I get any points for that)
This isn't the place we should spend resources. The risks are tiny and attacks hard. HSTS and A+ TLS would be nice, but I don't see them as security sensitive. The workers are the place where security is worthwhile considering, by not exposing resources that can do bad things.. 

----

Risk Management
---------------
* [ ] The service must have performed a Rapid Risk Assessment and have a Risk Record bug
* [ ] Public staging and production endpoints must be added to the [security baseline](https://github.com/mozilla-services/foxsec/blob/master/services/README.md)
 
Infrastructure
--------------
 
* [x] Access and application logs must be archived for a minimum of 90 days
* [x] Use [Modern](https://wiki.mozilla.org/Security/Server_Side_TLS#Modern_compatibility) or [Intermediate](https://wiki.mozilla.org/Security/Server_Side_TLS#Intermediate_compatibility) TLS
* [ ] Set HSTS to 31536000 (1 year)
  * `strict-transport-security: max-age=31536000`
* [ ] ~~Set HPKP to 5184000 (60 days)~~
  * `Public-Key-Pins: max-age=5184000; pin-sha256="WoiWRyIOVNa9ihaBciRSC7XHjliYS9VwUGOIud4PB18="; pin-sha256="r/mIkG3eEpVdm+u/ko/cwxzOMo1bk4TyHIlByibiA5E="; pin-sha256="YLh1dUR9y6Kja30RrAn7JKnbQG/uEtLMkBgFF2Fuihg="; pin-sha256="sRHdihwgkaib1P1gxX8HFszlD+7/gTfNvuAybgLPNis=";`
    * Start with max-age set to 5 minutes (`max-age=300`) and increase progressively
    * The first two pins are for Digicert EV and DV roots, the last two are for Let's Encrypt X3 and X4 intermediates (LE is only used for backup)
  * [ ] ~~If the service is not hosted under `services.mozilla.com`, it must be manually added to [Firefox's preloaded pins](https://dxr.mozilla.org/mozilla-central/source/security/manager/tools/PreloadedHPKPins.json#184).~~
* ~~If service has an admin panels, it must:~~
  * [ ] ~~only be available behind Mozilla VPN (which provides MFA)~~
  * [ ] ~~require Auth0 authentication~~
 
Development
-----------
* [ ] Sign all release tags, and ideally commits as well
  * Developers should [configure git to sign all tags](http://micropipes.com/blog//2016/08/31/signing-your-commits-on-github-with-a-gpg-key/) and upload their PGP fingerprint to https://login.mozilla.com
  * The signature verification will eventually become a requirement to shipping a release to staging & prod: the tag being deployed in the pipeline must have a matching tag in git signed by a project owner. This control is designed to reduce the risk of a 3rd party GitHub integration from compromising our source code.
* [ ] Keep 3rd-party libraries up to date
  * Use [NSP](https://nodesecurity.io/) or [GreenKeeper](https://greenkeeper.io/ Greenkeeper) for NodeJS applications
  * For Python applications, enable pyup security updates:
    * Add a pyup config to your repo (example config: https://github.com/mozilla-services/antenna/blob/master/.pyup.yml)
    * From the "add a team" dropdown for your repo add the relevant "Approved Mozilla PyUp Configuration" team for your github org (e.g. for [mozilla](https://github.com/orgs/mozilla/teams/approved-mozilla-pyup-configuration) and [mozilla-services](https://github.com/orgs/mozilla-services/teams/approved-mozilla-pyup-configuration)) and grant it write permission.
    * Notify secops@mozilla.com to enable the integration in pyup
    * Consider using ``pip list --outdated`` or [requires.io](https://requires.io/) too
* [ ] Integrate static code analysis in CI, and avoid merging code with issues
    * Javascript applications should use ESLint with the [Mozilla ruleset](https://developer.mozilla.org/en-US/docs/ESLint)
    * Python applications should use [Bandit](https://github.com/openstack/bandit)
    * Go applications should use the [Go Meta Linter](https://github.com/alecthomas/gometalinter)
    * Use whitelisting mechanisms in these tools to deal with false positives
 
Dual Sign Off
------------
* [ ] ~~Services that push data to Firefox clients must require a dual sign off on every change, implemented in their admin panels~~
  * This mechanism must be reviewed and approved by the Firefox Operations Security team before being enabled in production
 
Logging
-------
* [x] Publish detailed logs in [mozlog](https://github.com/mozilla-services/Dockerflow/blob/master/docs/mozlog.md) format (**APP-MOZLOG**)
  * Business logic must be logged with app specific codes (see [FxA](https://github.com/mozilla/fxa-auth-server/blob/master/docs/api.md#defined-errors))
  * Access control failures must be logged at WARN level
 
Security Headers
----------------
* [ ] ~~Must have a CSP with~~
  * [ ] ~~a report-uri pointing to the service's own `/__cspreport__` endpoint~~
  * [ ] ~~web API responses should return `default-src 'none'; frame-ancestors 'none';~~ base-uri 'none'; report-uri /__cspreport__` to disallowing all content rendering, framing, and report violations
  * [ ] ~~if default-src is not `none`, frame-src, and object-src should be `none` or only allow specific origins~~
  * [ ] ~~no use of unsafe-inline or unsafe-eval in script-src, style-src, and img-src~~
* [ ] ~~Web APIs must set a non-HTML content-type on all responses, including 300s, 400s and 500s~~
* [ ] ~~Set the Secure and HTTPOnly flags on [Cookies](https://wiki.mozilla.org/Security/Guidelines/Web_Security#Cookies), and use sensible Expiration~~
* [ ] Make sure your application gets an A+ on the [Mozilla Observatory](https://observatory.mozilla.org/)
* [ ] Verify your application doesn't have any failures on the [Security Baseline](https://github.com/mozilla-services/foxsec/blob/master/tools/baseline-scan/results/Baseline-Services.md).
  * Contact secops@ or ping 'psiinon' on github to document exceptions to the baseline, mark csrf exempt forms, etc.
* [ ] ~~Web APIs should export an OpenAPI (Swagger) to facilitate automated vulnerability tests~~
 
Databases
---------
* [ ] ~~All SQL queries must be parameterized, not concatenated~~
* [ ] ~~Applications must use accounts with limited GRANTS when connecting to databases~~
  * In particular, applications **must not use admin or owner accounts**, to decrease the impact of a sql injection vulnerability.
 
Common issues
-------------
* [ ] ~~User data must be [escaped for the right context](https://www.owasp.org/index.php/XSS_(Cross_Site_Scripting)_Prevention_Cheat_Sheet#XSS_Prevention_Rules_Summary) prior to reflecting it~~
  * When inserting user generated html into an html context:
    * Python applications should use [Bleach](https://github.com/mozilla/bleach)
    * Javascript applications should use [DOMPurify](https://github.com/cure53/DOMPurify/)
* [ ] ~~Apply sensible limits to user inputs, see [input validation](https://wiki.mozilla.org/WebAppSec/Secure_Coding_Guidelines#Input_Validation)~~
  * POST body size should be small (<500kB) unless explicitely needed
* [x] When managing permissions, make sure access controls are enforced server-side
* [x] If handling cryptographic keys, must have a mechanism to handle quarterly key rotations
  * Keys used to sign sessions don't need a rotation mechanism if destroying all sessions is acceptable in case of emergency.
* [ ] ~~Do not proxy requests from users without strong limitations and filtering (see [Pocket UserData vulnerability](https://www.gnu.gl/blog/Posts/multiple-vulnerabilities-in-pocket/)). Don't proxy requests to [link local, loopback, or private networks](https://en.wikipedia.org/wiki/Reserved_IP_addresses#IPv4) or DNS that resolves to addresses in those ranges (i.e. 169.254.0.0/16, 127.0.0.0/8, 10.0.0.0/8, 100.64.0.0/10, 172.16.0.0/12, 192.168.0.0/16, 198.18.0.0/15).~~
